"""Static Post Agent (spec § 6.5).

Produces a single image + caption + hashtags for a calendar entry. The image is
rendered with Pillow over a brand-accent background; the caption + hashtags are
generated by the LLM (or by a deterministic fallback if no key is set).
"""
from __future__ import annotations

import io
import json
import textwrap
import uuid
from typing import Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.agents.base import AgentResult, render_cross_sport_clause
from app.models.assets import Asset
from app.models.brand import Brand, BrandBrain
from app.models.content import CalendarEntry, ContentItem, ContentVariant
from app.models.products import Product
from app.pipeline.llm_gateway import LLMTier, complete
from app.pipeline.storage import get_storage, new_key


WIDTH, HEIGHT = 1080, 1350  # IG portrait


def _render_card(title: str, accent: str, sport: str) -> bytes:
    from PIL import Image, ImageDraw, ImageFont

    img = Image.new("RGB", (WIDTH, HEIGHT), color="#0a0a0a")
    draw = ImageDraw.Draw(img)

    # accent block
    draw.rectangle([0, HEIGHT - 220, WIDTH, HEIGHT], fill=accent)

    # try a built-in font; fall back to default
    try:
        font_title = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial Bold.ttf", 64)
        font_sport = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", 28)
    except Exception:
        font_title = ImageFont.load_default()
        font_sport = ImageFont.load_default()

    # sport pill
    draw.text((48, 48), sport.upper(), fill=accent, font=font_sport)

    # wrap title
    wrapper = textwrap.TextWrapper(width=22)
    lines = wrapper.wrap(title)[:5]
    y = 220
    for line in lines:
        draw.text((48, y), line, fill="white", font=font_title)
        y += 80

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _llm_copy(
    brand: Brand, brain: BrandBrain | None, angle: str, product: Optional[Product],
    overrides=None,
) -> tuple[dict, AgentResult]:
    from app.core.config import settings
    from app.agents._overrides import Overrides, apply_to_system, max_tokens_for, tier_for

    ov = overrides or Overrides()
    system = (
        render_cross_sport_clause(sport=brand.sport, brand_name=brand.name)
        + "\nYou are the Static Post agent. Write a punchy, on-brand caption for one Instagram-style image post.\n"
        + "Output ONLY JSON: {\"headline\": str, \"caption\": str, \"hashtags\": [str, ...], \"cta\": str}.\n"
        + "Caption ≤ 280 chars. 6–10 hashtags. CTA is 4–8 words."
    )
    system = apply_to_system(system, ov)
    voice = (brain.voice if brain else "") or "Clear, useful, non-hypey."
    user = f"Brand: {brand.name} (sport={brand.sport})\nVoice: {voice}\nAngle: {angle}\n"
    if product:
        user += f"Featured product: {product.title} (SKU {product.sku}, ${product.price})\n"
    if not settings.OPENROUTER_API_KEY:
        copy = {
            "headline": angle[:80],
            "caption": f"{angle} — built for {brand.sport} players who want results.",
            "hashtags": [f"#{brand.sport}", "#training", "#gear", f"#{brand.name.replace(' ', '').lower()}"],
            "cta": "Shop the link in bio.",
        }
        return copy, AgentResult(output=copy, model="fallback")
    res = complete(
        tier=tier_for(LLMTier.DRAFTING, ov.model),
        system=system, user=user, json_mode=True,
        max_tokens=max_tokens_for(600, ov.length),
    )
    try:
        copy = res.json_data or json.loads(res.content)
    except (json.JSONDecodeError, AttributeError):
        copy = {"headline": angle, "caption": angle, "hashtags": [f"#{brand.sport}"], "cta": "Shop now"}
    return copy, AgentResult(
        output=copy, tokens_in=res.tokens_in, tokens_out=res.tokens_out,
        cost_usd=res.cost_usd, model=res.model,
    )


class StaticPostAgent:
    name = "static_post"

    def run(self, db: Session, brand_id: uuid.UUID, entry_id: uuid.UUID) -> dict:
        entry = db.get(CalendarEntry, entry_id)
        if not entry or entry.brand_id != brand_id:
            raise ValueError("calendar entry not found")
        brand = db.get(Brand, brand_id)
        if brand is None:
            raise ValueError("brand not found")
        brain = db.execute(select(BrandBrain).where(BrandBrain.brand_id == brand_id)).scalar_one_or_none()
        product = None
        if entry.product_ids:
            product = db.get(Product, uuid.UUID(entry.product_ids[0]))

        from app.agents._overrides import parse
        copy, agent_result = _llm_copy(brand, brain, entry.angle, product, overrides=parse(entry.reason))

        # render image
        accent = brand.accent_color or "#CCFF00"
        img_bytes = _render_card(copy.get("headline") or entry.angle, accent, brand.sport)
        key = new_key(brand_id, "image", "png")
        storage = get_storage()
        url = storage.write_bytes(key, img_bytes)

        item = ContentItem(
            brand_id=brand_id,
            platform=entry.platform,
            content_type=entry.content_type,
            angle=entry.angle,
            product_ids=entry.product_ids,
            payload={
                "headline": copy.get("headline"),
                "caption": copy.get("caption"),
                "hashtags": copy.get("hashtags", []),
                "cta": copy.get("cta"),
                "image_url": url,
                "image_key": key,
            },
            status="drafted",
            agent_name=self.name,
            created_by="ai",
        )
        db.add(item)
        db.flush()

        db.add(ContentVariant(content_item_id=item.id, label="A", payload=item.payload))
        # generate B variant for A/B test (different hook / CTA, same image)
        from app.agents._ab import make_b_variant_for_caption
        b_payload = make_b_variant_for_caption(
            brand_sport=brand.sport,
            brand_voice=(brain.voice if brain else ""),
            angle=entry.angle,
            a_payload=item.payload,
        )
        db.add(ContentVariant(content_item_id=item.id, label="B", payload=b_payload))

        asset = Asset(
            brand_id=brand_id,
            content_item_id=item.id,
            kind="image",
            storage_key=key,
            mime="image/png",
            width=WIDTH,
            height=HEIGHT,
            meta={"agent": self.name},
        )
        db.add(asset)

        entry.content_item_id = item.id
        entry.status = "drafted"
        db.commit()

        return {
            "content_item_id": str(item.id),
            "image_url": url,
            "cost_usd": agent_result.cost_usd,
            "model": agent_result.model,
        }
